# Generated by Django 3.2.6 on 2021-08-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalid', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Sheep', 'Sheep')], default='Sheep', max_length=10)),
                ('breed', models.CharField(choices=[('Merino', 'Merino')], default='Merino', max_length=10)),
                ('dob', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'animalid', 'category', 'breed', 'dob')},
            },
        ),
    ]
