# Generated by Django 3.2.6 on 2021-08-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='dob',
            new_name='vacdate',
        ),
        migrations.AddField(
            model_name='animal',
            name='interval',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='nextdate',
            field=models.DateField(default=datetime.today().strftime('%Y-%m-%d')),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('user', 'animalid', 'category', 'breed', 'vacdate', 'interval')},
        ),
    ]
