# Generated by Django 3.2.6 on 2021-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210807_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nextdate',
            field=models.DateField(default='2021-08-01'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vacdate',
            field=models.DateField(default='2021-08-01'),
        ),
    ]
