# Generated by Django 3.2.6 on 2021-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210807_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(default='Merino', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(default='Sheep', max_length=10),
        ),
    ]
